apiVersion: v1
kind: ConfigMap
metadata:
  name: lamp1
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.4.json"
  data: |-
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "k8s",
          "virtualAddress": {
            "bindAddr": "192.168.166.110",
            "port": 80
          }
        },
        "backend": {
          "serviceName": "lamp1",
          "servicePort": 80,
          "healthMonitors": [{
            "interval": 30,
            "protocol": "http",
            "send": "GET",
            "timeout": 91
          }]
        }
      }
    }
