apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milano-lab-gluster-cluster-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: milano-lab-glfs1-storage
