baseURL = "https://www.x-wide.cloud"
languageCode = "en-us"
title = "F5 / NGINX / Shape Security"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

[taxonomies]
  tag = "tags"

[author]
	name = "F5 Networks"

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "F5 - Application Services, every app, everywhere"

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	#email = "#"
        #facebook = "#"
        twitter = "https://twitter.com/F5Networks"
	#instagram = ""
	#tumblr = "#"
	#reddit = "#"
	#pinterest = "#"
	youtube = "https://www.youtube.com/user/f5networksinc"
	#weibo = "#"
	#vk = "#"
	linkedin = "https://www.linkedin.com/company/f5-networks"

	# Writing
        #medium = "#"
	#blogger = "#"
	#wordpress = "#"

	# Creative & Visual
        #dribbble = "#"
	#behance = "#"
	#deviantart = "#"
	#flickr = "#"

	# Programming
        github = "https://github.com/f5networks"
	#stackoverflow = "#"
	#gitlab = "#"
	#codepen = "#"

# Add your Disqus shortname here.
disqusShortname = ""      

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
